### ISSUE TITLE
Add "Enable file tracking" option

### ISSUE THREAD

**Issue by brotkrueml** [brotkrueml/typo3-matomo-integration#25]
Matomo 5 introduces a new option "enableFileTracking":
https://matomo.org/faq/how-to/enable-file-protocol-tracking/

- [x] Add "Enable file tracking" to site configuration options with the hint "Only in Matomo 5"
- [x] Implement logic to output the new option.
- [x] Describe option in documentation
- [x] Add entry to changelog
