### ISSUE TITLE
Store JavaScript tracking configuration in file to use with CSP

### ISSUE THREAD

**Issue by brotkrueml** [brotkrueml/typo3-matomo-integration#7]
As an administrator I want to use a strict content security policy without inline JavaScript. For this, the tracking code has to be stored in the filesystem. See also: https://matomo.org/faq/general/faq_20904/

- [ ] An option to store the tracking code in the filesystem is available.
- [ ] If the option is enabled the generated tracking code is stored as file.
- [ ] As the code can change from page to page (for example custom dimensions to categorise pages) a hash is added to the file name (which hashes the content and ensures also that the filesystem is not flooded with files with the same content).
- [ ] The EnrichScriptTagEvent is considered (see #5).
- [ ] The documentation is adjusted. Also a hint is available, that the CSP headers must be set manually in the webserver.
- [ ] A feature entry to the changelog is added.

**Further enhancements:** When TYPO3 has the possibility to add CSP headers via backend/API, a nonce can be added to the inline script. See: https://forge.typo3.org/issues/87423 and https://forge.typo3.org/issues/87420.

**Comment by tehplague** [comment]
Could you at least add a `$nonce` property to `EnrichScriptTagEvent` so that we can dynamically create a nonce and use that in generated script tags? Currently it only allows `id`, `type` and `data-...` attributes.

**Comment by brotkrueml** [comment]
> Could you at least add a `$nonce` property to `EnrichScriptTagEvent` so that we can dynamically create a nonce and use that in generated script tags? Currently it only allows `id`, `type` and `data-...` attributes.

@tehplague Please open a separate issue for this feature request. Interesting is how you inject the nonce into the HTTP header. Also a PR including a full use case in the docs is very welcome :-)

**Comment by tehplague** [comment]
I solved that using a PSR-15 middleware but at the moment my main problem is that the extension's generated script tags are cached - rendering my nonces useless. Your concept above might suffer from the same problem. But you're right in that I shall discuss the `$nonce`-specific concerns in a separate thread.

**Comment by ohader** [comment]
Dynamic nonces have been addressed with:
* https://review.typo3.org/c/Packages/TYPO3.CMS/+/78660
* https://review.typo3.org/c/Packages/TYPO3.CMS/+/79058
